import os

class PatientJourneyConstantsNamespace:
    __slots__ = ()
    PROJECT_DIR = os.path.dirname(__file__)
    DATA_FILES_PATH = os.path.join(PROJECT_DIR, '00_data_files')

    # 2021 data

    DIAGBH2021_FILENAME = '2021_diagbh.txt'
    DIAGBH2021_FILEPATH = os.path.join(DATA_FILES_PATH, DIAGBH2021_FILENAME)

    DIAGMD2021_FILENAME = '2021_diagmd.txt'
    DIAGMD2021_FILEPATH = os.path.join(DATA_FILES_PATH, DIAGMD2021_FILENAME)

    PROCMD2021_FILENAME = '2021_procmd.txt'
    PROCMD2021_FILEPATH = os.path.join(DATA_FILES_PATH, PROCMD2021_FILENAME)

    RX2021_FILENAME = '2021_rx.txt'
    RX2021_FILEPATH = os.path.join(DATA_FILES_PATH, RX2021_FILENAME)

    SERVBH2021_FILENAME = '2021_servbh.txt'
    SERVBH2021_FILEPATH = os.path.join(DATA_FILES_PATH, SERVBH2021_FILENAME)

    SERVMD2021_FILENAME = '2021_servmd.txt'
    SERVMD2021_FILEPATH = os.path.join(DATA_FILES_PATH, SERVMD2021_FILENAME)

    # 2022 data

    DIAGBH2022_FILENAME = '2022_diagbh.txt'
    DIAGBH2022_FILEPATH = os.path.join(DATA_FILES_PATH, DIAGBH2022_FILENAME)

    DIAGMD2022_FILENAME = '2022_diagmd.txt'
    DIAGMD2022_FILEPATH = os.path.join(DATA_FILES_PATH, DIAGMD2022_FILENAME)

    PROCMD2022_FILENAME = '2022_procmd.txt'
    PROCMD2022_FILEPATH = os.path.join(DATA_FILES_PATH, PROCMD2022_FILENAME)

    RX2022_FILENAME = '2022_rx.txt'
    RX2022_FILEPATH = os.path.join(DATA_FILES_PATH, RX2022_FILENAME)

    SERVBH2022_FILENAME = '2022_servbh.txt'
    SERVBH2022_FILEPATH = os.path.join(DATA_FILES_PATH, SERVBH2022_FILENAME)

    SERVMD2022_FILENAME = '2022_servmd.txt'
    SERVMD2022_FILEPATH = os.path.join(DATA_FILES_PATH, SERVMD2022_FILENAME)

    # Dummy Ids

    DUMMY_IDS_DIAG_FILENAME = 'level1_dummy_ids_diag.txt'
    DUMMY_IDS_DIAG_FILEPATH = os.path.join(DATA_FILES_PATH, DUMMY_IDS_DIAG_FILENAME)

    DUMMY_IDS_PROC_FILENAME = 'level1_dummy_ids_proc.txt'
    DUMMY_IDS_PROC_FILEPATH = os.path.join(DATA_FILES_PATH, DUMMY_IDS_PROC_FILENAME)

    DUMMY_IDS_RX_FILENAME = 'level1_dummy_ids_rx.txt'
    DUMMY_IDS_RX_FILEPATH = os.path.join(DATA_FILES_PATH, DUMMY_IDS_RX_FILENAME)

    DUMMY_IDS_SERV_FILENAME = 'level1_dummy_ids_service.txt'
    DUMMY_IDS_SERV_FILEPATH = os.path.join(DATA_FILES_PATH, DUMMY_IDS_SERV_FILENAME)
